Updates for upcoming Mailscanner 5.2.3-1 (#456)
* Updates
Dependencies for latest SpamAssassin
Support for latest distributions
cpanminus by default

diff --git a/debian/usr/sbin/ms-configure b/debian/usr/sbin/ms-configure
--- a/debian/usr/sbin/ms-configure
+++ b/debian/usr/sbin/ms-configure
@@ -6,7 +6,7 @@
 # MailScanner via apt-get and CPAN based on user input.  
 #
 #
-# Updated: 2 Nov 2019
+# Updated: 16 Feb 2020
 # MailScanner Team <https://www.mailscanner.info>
 clear
 
@@ -199,10 +199,10 @@ if [ -z "${arg_MTA+x}" ]; then
         # sendmail
         MTAOPTION="sendmail sendmail-bin";
     elif [ $response -eq 2 ]; then
-        # sendmail
+        # postfix
         MTAOPTION="postfix";
     elif [ $response -eq 3 ]; then
-        # sendmail
+        # exim
         MTAOPTION="exim4-base";
     else
         MTAOPTION=
@@ -357,87 +357,86 @@ fi
 
 # base system packages
 BASEPACKAGES=();
-BASEPACKAGES+=('perl-doc');			BASEPACKAGES+=('libmailtools-perl');			BASEPACKAGES+=('re2c');
-BASEPACKAGES+=('curl');				BASEPACKAGES+=('libnet-cidr-lite-perl');        BASEPACKAGES+=('libmime-tools-perl');
-BASEPACKAGES+=('wget');				BASEPACKAGES+=('libtest-manifest-perl');		BASEPACKAGES+=('libnet-cidr-perl');
-BASEPACKAGES+=('tar');				BASEPACKAGES+=('libdata-dump-perl');			BASEPACKAGES+=('libsys-syslog-perl');
-BASEPACKAGES+=('binutils');			BASEPACKAGES+=('libbusiness-isbn-perl');		BASEPACKAGES+=('libio-stringy-perl');
-BASEPACKAGES+=('unrar');			BASEPACKAGES+=('libdbd-mysql-perl');			BASEPACKAGES+=('perl-modules');
-BASEPACKAGES+=('gcc');				BASEPACKAGES+=('libconvert-tnef-perl');			BASEPACKAGES+=('libdbd-mysql-perl');
-BASEPACKAGES+=('make');				BASEPACKAGES+=('libdbd-sqlite3-perl');			BASEPACKAGES+=('libencode-detect-perl');
-BASEPACKAGES+=('patch');			BASEPACKAGES+=('libfilesys-df-perl');			BASEPACKAGES+=('libc6-dev');
-BASEPACKAGES+=('antiword');			BASEPACKAGES+=('libarchive-zip-perl');			BASEPACKAGES+=('libconfig-yaml-perl');
-BASEPACKAGES+=('pyzor');			BASEPACKAGES+=('libole-storage-lite-perl');		BASEPACKAGES+=('libsys-sigaction-perl');
-BASEPACKAGES+=('razor');			BASEPACKAGES+=('libinline-perl');				BASEPACKAGES+=('libmail-imapclient-perl');
-BASEPACKAGES+=('tnef');				BASEPACKAGES+=('libmail-spf-perl');				BASEPACKAGES+=('libtest-pod-coverage-perl');
-BASEPACKAGES+=('gzip');				BASEPACKAGES+=('libnetaddr-ip-perl');			BASEPACKAGES+=('libfile-sharedir-install-perl');
-BASEPACKAGES+=('unzip');			BASEPACKAGES+=('libnet-ldap-perl');				BASEPACKAGES+=('libsys-hostname-long-perl');
-BASEPACKAGES+=('openssl');			BASEPACKAGES+=('libmail-dkim-perl');			BASEPACKAGES+=('libhtml-tokeparser-simple-perl');
-BASEPACKAGES+=('perl');				BASEPACKAGES+=('libbusiness-isbn-data-perl');	BASEPACKAGES+=('libnet-dns-resolver-programmable-perl');
-BASEPACKAGES+=('p7zip-full');       BASEPACKAGES+=('libgeo-ip-perl');               BASEPACKAGES+=('libnet-patricia-perl');
-BASEPACKAGES+=('arj');              BASEPACKAGES+=('lhasa');                        BASEPACKAGES+=('bzip2');  
-BASEPACKAGES+=('cabextract');       BASEPACKAGES+=('cpio');                         BASEPACKAGES+=('file');  
-BASEPACKAGES+=('gzip');             BASEPACKAGES+=('nomarch');                      BASEPACKAGES+=('pax');  
-BASEPACKAGES+=('rar');              BASEPACKAGES+=('unrar');                        BASEPACKAGES+=('unzip');  
-BASEPACKAGES+=('zip');              BASEPACKAGES+=('zoo');                          BASEPACKAGES+=('libsendmail-pmilter-perl');
-BASEPACKAGES+=('libdb-dev');        BASEPACKAGES+=('libmime-tools-perl');           BASEPACKAGES+=('libtest-deep-perl');
-
-if [ "$parsedCommands" -gt 0 ]; then
-    BASEPACKAGES+=('cpanminus');
-fi
-
-# install these from array above in case one of the 
-# packages produce an error
-#
-#"curl wget tar binutils libc6-dev gcc make patch gzip unzip openssl perl perl-doc libdbd-mysql-perl libconvert-tnef-perl libdbd-sqlite3-perl libfilesys-df-perl libmailtools-perl libmime-tools-perl libnet-cidr-perl libsys-syslog-perl libio-stringy-perl perl-modules libdbd-mysql-perl libencode-detect-perl unrar antiword libarchive-zip-perl libconfig-yaml-perl libole-storage-lite-perl libsys-sigaction-perl pyzor razor tnef libinline-perl libmail-imapclient-perl libtest-pod-coverage-perl libfile-sharedir-install-perl libmail-spf-perl libnetaddr-ip-perl libsys-hostname-long-perl libhtml-tokeparser-simple-perl libmail-dkim-perl libnet-ldap-perl libnet-dns-resolver-programmable-perl libnet-cidr-lite-perl libtest-manifest-perl libdata-dump-perl libbusiness-isbn-data-perl libbusiness-isbn-perl libtest-simple-perl";
+BASEPACKAGES+=('perl-doc');						BASEPACKAGES+=('libmailtools-perl');			BASEPACKAGES+=('re2c');
+BASEPACKAGES+=('curl');							BASEPACKAGES+=('libnet-cidr-lite-perl');        BASEPACKAGES+=('libmime-tools-perl');
+BASEPACKAGES+=('wget');							BASEPACKAGES+=('libtest-manifest-perl');		BASEPACKAGES+=('libnet-cidr-perl');
+BASEPACKAGES+=('tar');							BASEPACKAGES+=('libdata-dump-perl');			BASEPACKAGES+=('libsys-syslog-perl');
+BASEPACKAGES+=('binutils');						BASEPACKAGES+=('libbusiness-isbn-perl');		BASEPACKAGES+=('libio-stringy-perl');
+BASEPACKAGES+=('unrar');						BASEPACKAGES+=('libdbd-mysql-perl');			BASEPACKAGES+=('perl-modules');
+BASEPACKAGES+=('gcc');							BASEPACKAGES+=('libconvert-tnef-perl');			BASEPACKAGES+=('libdbd-mysql-perl');
+BASEPACKAGES+=('make');							BASEPACKAGES+=('libdbd-sqlite3-perl');			BASEPACKAGES+=('libencode-detect-perl');
+BASEPACKAGES+=('patch');						BASEPACKAGES+=('libfilesys-df-perl');			BASEPACKAGES+=('libc6-dev');
+BASEPACKAGES+=('antiword');						BASEPACKAGES+=('libarchive-zip-perl');			BASEPACKAGES+=('libconfig-yaml-perl');
+BASEPACKAGES+=('pyzor');						BASEPACKAGES+=('libole-storage-lite-perl');		BASEPACKAGES+=('libsys-sigaction-perl');
+BASEPACKAGES+=('razor');						BASEPACKAGES+=('libinline-perl');				BASEPACKAGES+=('libmail-imapclient-perl');
+BASEPACKAGES+=('tnef');							BASEPACKAGES+=('libmail-spf-perl');				BASEPACKAGES+=('libtest-pod-coverage-perl');
+BASEPACKAGES+=('gzip');							BASEPACKAGES+=('libnetaddr-ip-perl');			BASEPACKAGES+=('libfile-sharedir-install-perl');
+BASEPACKAGES+=('unzip');						BASEPACKAGES+=('libnet-ldap-perl');				BASEPACKAGES+=('libsys-hostname-long-perl');
+BASEPACKAGES+=('openssl');						BASEPACKAGES+=('libmail-dkim-perl');			BASEPACKAGES+=('libhtml-tokeparser-simple-perl');
+BASEPACKAGES+=('perl');							BASEPACKAGES+=('libbusiness-isbn-data-perl');	BASEPACKAGES+=('libnet-dns-resolver-programmable-perl');
+BASEPACKAGES+=('p7zip-full');					BASEPACKAGES+=('libgeo-ip-perl');				BASEPACKAGES+=('libnet-patricia-perl');
+BASEPACKAGES+=('arj');							BASEPACKAGES+=('lhasa');						BASEPACKAGES+=('bzip2');  
+BASEPACKAGES+=('cabextract');					BASEPACKAGES+=('cpio');							BASEPACKAGES+=('file');  
+BASEPACKAGES+=('gzip');							BASEPACKAGES+=('nomarch');						BASEPACKAGES+=('pax');  
+BASEPACKAGES+=('rar');							BASEPACKAGES+=('unrar');						BASEPACKAGES+=('unzip');  
+BASEPACKAGES+=('zip');							BASEPACKAGES+=('zoo');							BASEPACKAGES+=('libsendmail-pmilter-perl');
+BASEPACKAGES+=('libdb-dev');					BASEPACKAGES+=('libmime-tools-perl');			BASEPACKAGES+=('libtest-deep-perl');
+BASEPACKAGES+=('cpanminus');					BASEPACKAGES+=('libmath-int64-perl');			BASEPACKAGES+=('libpath-class-perl');
+BASEPACKAGES+=('libtest-fatal-perl');			BASEPACKAGES+=('libnamespace-autoclean-perl');	BASEPACKAGES+=('librole-tiny-perl');
+BASEPACKAGES+=('libdata-dumper-concise-perl');	BASEPACKAGES+=('libdatetime-perl');				BASEPACKAGES+=('libtest-warnings-perl');
+BASEPACKAGES+=('libautodie-perl');				BASEPACKAGES+=('libtest-requires-perl');		BASEPACKAGES+=('libclone-pp-perl');
+BASEPACKAGES+=('libfile-homedir-perl');			BASEPACKAGES+=('libsort-naturally-perl');		BASEPACKAGES+=('libjson-maybexs-perl');
+BASEPACKAGES+=('libtest-leaktrace-perl');		BASEPACKAGES+=('libthrowable-perl');			BASEPACKAGES+=('libmaxminddb-dev');
 
 # the array of perl modules needed
 ARMOD=();
-ARMOD+=('Archive::Tar');		ARMOD+=('Archive::Zip');		ARMOD+=('bignum');
-ARMOD+=('Carp');				ARMOD+=('Compress::Zlib');		ARMOD+=('Compress::Raw::Zlib');
-ARMOD+=('Convert::BinHex');		ARMOD+=('Convert::TNEF');		ARMOD+=('Data::Dumper');
-ARMOD+=('Date::Parse');			ARMOD+=('DBD::SQLite');			ARMOD+=('DBI');
-ARMOD+=('Digest::HMAC');		ARMOD+=('Digest::MD5');			ARMOD+=('Digest::SHA1');
-ARMOD+=('DirHandle');			ARMOD+=('ExtUtils::MakeMaker');	ARMOD+=('Fcntl');
-ARMOD+=('File::Basename');		ARMOD+=('File::Copy');			ARMOD+=('File::Path');
-ARMOD+=('File::Spec');			ARMOD+=('File::Temp');			ARMOD+=('FileHandle');
-ARMOD+=('Filesys::Df');			ARMOD+=('Getopt::Long');		ARMOD+=('Inline::C');
-ARMOD+=('IO');					ARMOD+=('IO::File');			ARMOD+=('IO::Pipe');
-ARMOD+=('IO::Stringy');			ARMOD+=('HTML::Entities');		ARMOD+=('HTML::Parser');
-ARMOD+=('HTML::Tagset');		ARMOD+=('HTML::TokeParser');	ARMOD+=('Mail::Field');
-ARMOD+=('Mail::Header');		ARMOD+=('Mail::IMAPClient');	ARMOD+=('Mail::Internet');
-ARMOD+=('Math::BigInt');		ARMOD+=('Math::BigRat');		ARMOD+=('MIME::Base64');
-ARMOD+=('MIME::Decoder');		ARMOD+=('MIME::Decoder::UU');	ARMOD+=('MIME::Head');
-ARMOD+=('MIME::Parser');		ARMOD+=('MIME::QuotedPrint');	ARMOD+=('MIME::Tools');
-ARMOD+=('MIME::WordDecoder');	ARMOD+=('Net::CIDR');			ARMOD+=('Net::DNS');
-ARMOD+=('Net::IP');				ARMOD+=('OLE::Storage_Lite');	ARMOD+=('Pod::Escapes');
-ARMOD+=('Pod::Simple');			ARMOD+=('POSIX');				ARMOD+=('Scalar::Util');
-ARMOD+=('Socket');				ARMOD+=('Storable');			ARMOD+=('Test::Harness');
-ARMOD+=('Test::Pod');			ARMOD+=('Test::Simple');		ARMOD+=('Time::HiRes');
-ARMOD+=('Time::localtime');		ARMOD+=('Sys::Hostname::Long');	ARMOD+=('Sys::SigAction');
-ARMOD+=('Sys::Syslog');			ARMOD+=('Env');
-
-MODSA='Mail::SpamAssassin';
-
-# not required but nice to have
-ARMODAFTERSA=();
-ARMODAFTERSA+=('bignum');
-ARMODAFTERSA+=('Data::Dump');		ARMODAFTERSA+=('DB_File');				ARMODAFTERSA+=('DBD::SQLite');
-ARMODAFTERSA+=('DBI');				ARMODAFTERSA+=('Digest');				ARMODAFTERSA+=('Encode::Detect');
-ARMODAFTERSA+=('Error');			ARMODAFTERSA+=('ExtUtils::CBuilder');	ARMODAFTERSA+=('ExtUtils::ParseXS');
-ARMODAFTERSA+=('Getopt::Long');		ARMODAFTERSA+=('Inline');				ARMODAFTERSA+=('IO::String');
-ARMODAFTERSA+=('IO::Zlib');			ARMODAFTERSA+=('IP::Country');			ARMODAFTERSA+=('Mail::SPF');
-ARMODAFTERSA+=('Mail::SPF::Query');	ARMODAFTERSA+=('Module::Build');		ARMODAFTERSA+=('Net::CIDR::Lite');
-ARMODAFTERSA+=('Net::DNS');			ARMODAFTERSA+=('Net::LDAP');			ARMODAFTERSA+=('Net::DNS::Resolver::Programmable');
-ARMODAFTERSA+=('NetAddr::IP');		ARMODAFTERSA+=('Parse::RecDescent');	ARMODAFTERSA+=('Test::Harness');
-ARMODAFTERSA+=('Test::Manifest');	ARMODAFTERSA+=('Text::Balanced');		ARMODAFTERSA+=('URI');
-ARMODAFTERSA+=('version');			ARMODAFTERSA+=('IO::Compress::Bzip2');  ARMODAFTERSA+=('Sendmail::PMilter');
+ARMOD+=('Archive::Tar');			ARMOD+=('Archive::Zip');			ARMOD+=('bignum');
+ARMOD+=('Carp');					ARMOD+=('Compress::Zlib');			ARMOD+=('Compress::Raw::Zlib');
+ARMOD+=('Convert::BinHex');			ARMOD+=('Convert::TNEF');			ARMOD+=('Data::Dumper');
+ARMOD+=('Date::Parse');				ARMOD+=('DBD::SQLite');				ARMOD+=('DBI');
+ARMOD+=('Digest::HMAC');			ARMOD+=('Digest::MD5');				ARMOD+=('Digest::SHA1');
+ARMOD+=('DirHandle');				ARMOD+=('ExtUtils::MakeMaker');		ARMOD+=('Fcntl');
+ARMOD+=('File::Basename');			ARMOD+=('File::Copy');				ARMOD+=('File::Path');
+ARMOD+=('File::Spec');				ARMOD+=('File::Temp');				ARMOD+=('FileHandle');
+ARMOD+=('Filesys::Df');				ARMOD+=('Getopt::Long');			ARMOD+=('Inline::C');
+ARMOD+=('IO');						ARMOD+=('IO::File');				ARMOD+=('IO::Pipe');
+ARMOD+=('IO::Stringy');				ARMOD+=('HTML::Entities');			ARMOD+=('HTML::Parser');
+ARMOD+=('HTML::Tagset');			ARMOD+=('HTML::TokeParser');		ARMOD+=('Mail::Field');
+ARMOD+=('Mail::Header');			ARMOD+=('Mail::IMAPClient');		ARMOD+=('Mail::Internet');
+ARMOD+=('Math::BigInt');			ARMOD+=('Math::BigRat');			ARMOD+=('MIME::Base64');
+ARMOD+=('MIME::Decoder');			ARMOD+=('MIME::Decoder::UU');		ARMOD+=('MIME::Head');
+ARMOD+=('MIME::Parser');			ARMOD+=('MIME::QuotedPrint');		ARMOD+=('MIME::Tools');
+ARMOD+=('MIME::WordDecoder');		ARMOD+=('Net::CIDR');				ARMOD+=('Net::DNS');
+ARMOD+=('Net::IP');					ARMOD+=('OLE::Storage_Lite');		ARMOD+=('Pod::Escapes');
+ARMOD+=('Pod::Simple');				ARMOD+=('POSIX');					ARMOD+=('Scalar::Util');
+ARMOD+=('Socket');					ARMOD+=('Storable');				ARMOD+=('Test::Harness');
+ARMOD+=('Test::Pod');				ARMOD+=('Test::Simple');			ARMOD+=('Time::HiRes');
+ARMOD+=('Time::localtime');			ARMOD+=('Sys::Hostname::Long');		ARMOD+=('Sys::SigAction');
+ARMOD+=('Sys::Syslog');				ARMOD+=('Env');						ARMOD+=('bignum');
+ARMOD+=('Data::Dump');				ARMOD+=('DB_File');					ARMOD+=('DBD::SQLite');
+ARMOD+=('DBI');						ARMOD+=('Digest');					ARMOD+=('Encode::Detect');
+ARMOD+=('Error');					ARMOD+=('ExtUtils::CBuilder');		ARMOD+=('ExtUtils::ParseXS');
+ARMOD+=('Getopt::Long');			ARMOD+=('Inline');					ARMOD+=('IO::String');
+ARMOD+=('IO::Zlib');				ARMOD+=('IP::Country');				ARMOD+=('Mail::SPF');
+ARMOD+=('Mail::SPF::Query');		ARMOD+=('Module::Build');			ARMOD+=('Net::CIDR::Lite');
+ARMOD+=('Net::DNS');				ARMOD+=('Net::LDAP');				ARMOD+=('Net::DNS::Resolver::Programmable');
+ARMOD+=('NetAddr::IP');				ARMOD+=('Parse::RecDescent');		ARMOD+=('Test::Harness');
+ARMOD+=('Test::Manifest');			ARMOD+=('Text::Balanced');			ARMOD+=('URI');
+ARMOD+=('version');					ARMOD+=('IO::Compress::Bzip2');		ARMOD+=('Sendmail::PMilter');
+ARMOD+=('Math::Int64');				ARMOD+=('IP::Country::DB_File');	ARMOD+=('namespace::autoclean');
+ARMOD+=('Data::IEEE754');			ARMOD+=('Data::Printer');			ARMOD+=('Data::Validate::IP');
+ARMOD+=('List::AllUtils');			ARMOD+=('List::SomeUtils');			ARMOD+=('Test::Tester');
+ARMOD+=('List::UtilsBy');			ARMOD+=('MaxMind::DB::Metadata');	ARMOD+=('MaxMind::DB::Reader');
+ARMOD+=('Module::Runtime');			ARMOD+=('Moo');						ARMOD+=('MooX::StrictConstructor');
+ARMOD+=('Role::Tiny');				ARMOD+=('strictures');				ARMOD+=('MaxMind::DB::Reader::XS');
+ARMOD+=('Sub::Quote');				ARMOD+=('Math::Int128');			ARMOD+=('Net::Works::Network');
 
 # additional spamassassin plugins
-ARMODAFTERSA+=('Mail::SpamAssassin::Plugin::Rule2XSBody');
-ARMODAFTERSA+=('Mail::SpamAssassin::Plugin::DCC');
-ARMODAFTERSA+=('Mail::SpamAssassin::Plugin::Pyzor');
-
+SAMOD=();
+SAMOD+=('Mail::SpamAssassin')
+SAMOD+=('Mail::SpamAssassin::Plugin::Rule2XSBody');
+SAMOD+=('Mail::SpamAssassin::Plugin::DCC');
+SAMOD+=('Mail::SpamAssassin::Plugin::Pyzor');
 
 (
 clear
@@ -522,26 +521,38 @@ timewait 2
 PMODWAIT=0
 
 # CPAN automation invoked?
-if [ -z "${arg_installCPAN+x}" ]; then
-    AUTOCPAN=0
-else
-    if [ $CPANOPTION -eq 1 ]; then
-        AUTOCPAN=1
-        # Install cpanminus
-        $APTGET  -y install cpanminus
-        if [ $? -ne 0 ]; then
-            echo "Error installing cpanminus, falling back to perl invocation method."
-            AUTOCPAN=0
-        fi
-    else
+if [ $CPANOPTION -eq 1 ]; then
+    AUTOCPAN=1
+    # Install cpanminus
+    $APTGET  -y install cpanminus
+    if [ $? -ne 0 ]; then
+        echo "Error installing cpanminus, falling back to perl invocation method."
         AUTOCPAN=0
     fi
+else
+    AUTOCPAN=0
 fi
 
 # remediate
-if [ ${CPANOPTION} == 1 ]; then
+if [ ${CPANOPTION} -eq 1 ]; then
     #Install pre SpamAssassin modules
     for i in "${ARMOD[@]}"
+    do
+        perldoc -l ${i} >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            clear
+            echo "${i} is missing. Installing via CPAN ..."; echo;
+            timewait 1
+            if [ $AUTOCPAN -eq 0 ]; then
+                perl -MCPAN -e "CPAN::Shell->force(qw(install ${i} ));"
+            else
+                cpanm --force --no-interactive $i
+            fi
+        fi
+    done
+
+    #Install SpamAssassin modules
+    for i in "${SAMOD[@]}"
     do
         perldoc -l ${i} >/dev/null 2>&1
         if [ $? -ne 0 ]; then
@@ -561,58 +572,10 @@ if [ ${CPANOPTION} == 1 ]; then
         cpanm App::cpanoutdated
         cpan-outdated -p | cpanm --force --no-interactive
     fi
-
-    #Install SpamaAssassin, use standard cpan in normail install, or App::cpanminus in unattended install
-    perldoc -l ${MODSA} >/dev/null 2>&1
-    if [ $? -ne 0 ]; then
-        clear
-        echo "${MODSA} is missing. Installing via CPAN ..."; echo;
-        timewait 1
-        if [ $AUTOCPAN -eq 0 ]; then
-            perl -MCPAN -e "CPAN::Shell->force(qw(install ${MODSA} ));"
-        else
-            cpanm --no-interactive --force ${MODSA}
-        fi
-    fi
-
-    #Install post SpamAssassin modules
-    for i in "${ARMODAFTERSA[@]}"
-    do
-        perldoc -l ${i} >/dev/null 2>&1
-        if [ $? -ne 0 ]; then
-            clear
-            echo "${i} is missing. Installing via CPAN ..."; echo;
-            timewait 1
-            perl -MCPAN -e "CPAN::Shell->force(qw(install ${i} ));"
-        fi
-    done
-
-    # # Mail::ClamAV has broken version detection
-    # # Prepare to patch and install
-    # if [ $CAV -eq 1 ]; then
-    #     cpan -g Mail::ClamAV
-    #     package=$(find -name Mail-ClamAV*gz | tail -n1)
-    #     tar xzvf $package
-    #     packagedir=$(echo $package | sed -e 's/\.tar\.gz//')
-    #     patch -p1 $packagedir/Makefile.PL < patch.diff
-    #     cd $packagedir
-    #     perl Makefile.PL
-    #     make install
-    # fi
-
-    # Install MIME::Tools from CPAN even though rpm is present
-    # Fixes outdated MIME::Tools causing MailScanner to crash
-    clear
-    echo "Latest MIME::Tools is needed, Installing via CPAN ..."; echo;
-    timewait 1
-    perl -MCPAN -e "CPAN::Shell->force(qw(install MIME::Tools));"
-else
-  echo "WARNING: Outdated MIME::Tools may be present. You should fix this.";
-  PMODWAIT=5
 fi
 
 # check and notify of any missing modules
-ARMODALL=("${ARMOD[@]}" "${MODSA}" "${ARMODAFTERSA[@]}")
+ARMODALL=("${ARMOD[@]}" "${SAMOD}")
 for i in "${ARMODALL[@]}"
 do
     perldoc -l ${i} >/dev/null 2>&1
