Updates Dependencies for latest SpamAssassin Support for latest distributions cpanminus by default postfix by default

diff --git a/suse/usr/sbin/ms-configure b/suse/usr/sbin/ms-configure
--- a/suse/usr/sbin/ms-configure
+++ b/suse/usr/sbin/ms-configure
@@ -5,9 +5,9 @@
 # This script installs the required software for
 # MailScanner via zypper and CPAN based on user input.  
 #
-# Tested distributions:     OpenSUSE 13.2-42.3 (Leap 15.1 Pending)
+# Tested distributions:     OpenSUSE Leap 15.1
 #
-# Updated: 2 Nov 2019
+# Updated: 16 Feb 200
 # MailScanner Team <https://www.mailscanner.info>
 
 # clear the screen. yay!
@@ -189,23 +189,23 @@ echo "2 - postfix";
 echo "3 - exim";
 echo "N - Do not install";
 echo;
-echo "Recommended: 1 (sendmail)"; echo;
+echo "Recommended: 2 (postfix)"; echo;
 if [ -z "${arg_MTA+x}" ]; then
-    read -r -p "Install an MTA? [1] : " response
+    read -r -p "Install an MTA? [2] : " response
     if [[ $response =~ ^([nN][oO])$ ]]; then
         # do not install
         MTAOPTION=
     elif [ -z $response ]; then    
         # sendmail default
-        MTAOPTION="sendmail";
+        MTAOPTION="postfix";
     elif [ $response -eq 1 ]; then    
         # sendmail 
         MTAOPTION="sendmail";    
     elif [ $response -eq 2 ]; then    
-        # sendmail 
+        # postfix
         MTAOPTION="postfix";
     elif [ $response -eq 3 ]; then    
-        # sendmail 
+        # exim
         MTAOPTION="exim";        
     else
         MTAOPTION=
@@ -385,7 +385,7 @@ BASEPACKAGES="binutils gcc glibc-devel libaio1 make man-pages patch rpm tar time
 # Packages available in the suse base 13.2. If the user elects not to use EPEL or if the 
 # package is not available for their distro release it will be ignored during the install.
 #
-MOREPACKAGES="perl-Archive-Zip perl-Convert-BinHex perl-Convert-TNEF perl-DBD-SQLite perl-DBI perl-MIME-tools perl-Digest-HMAC perl-Digest-SHA1 perl-ExtUtils-MakeMaker perl-File-ShareDir-Install perl-File-Temp perl-Filesys-Df perl-Getopt-Long-Descriptive perl-IO-stringy perl-HTML-Parser perl-HTML-Tagset perl-Inline perl-Mail-DKIM perl-Mail-SPF perl-MailTools perl-Net-CIDR-Set perl-Net-DNS perl-Net-IP perl-OLE-Storage_Lite perl-Scalar-List-Utils perl-razor-agents perl-Sys-Hostname-Long perl-Sys-SigAction perl-Test-Pod perl-TimeDate perl-URI re2c perl-Encode-Detect perl-LDAP perl-IO-Compress-Bzip2 perl-Test-Simple p7zip";
+MOREPACKAGES="perl-Archive-Zip perl-Convert-BinHex perl-Convert-TNEF perl-DBD-SQLite perl-DBI perl-MIME-tools perl-Digest-HMAC perl-Digest-SHA1 perl-ExtUtils-MakeMaker perl-File-ShareDir-Install perl-File-Temp perl-Filesys-Df perl-Getopt-Long-Descriptive perl-IO-stringy perl-HTML-Parser perl-HTML-Tagset perl-Inline perl-Mail-DKIM perl-Mail-SPF perl-MailTools perl-Net-CIDR-Set perl-Net-DNS perl-Net-IP perl-OLE-Storage_Lite perl-Scalar-List-Utils perl-razor-agents perl-Sys-Hostname-Long perl-Sys-SigAction perl-Test-Pod perl-TimeDate perl-URI re2c perl-Encode-Detect perl-LDAP perl-IO-Compress-Bzip2 perl-Test-Simple p7zip perl-Math-Int64 perl-Path-Class perl-Test-Fatal perl-Test-Number-Delta perl-namespace-autoclean perl-Role-Tiny perl-Data-Dumper-Concise perl-DateTime perl-Test-Warnings perl-autodie perl-Test-Requires perl-Test-Tester perl-Clone-PP perl-File-HomeDir perl-Sort-Naturally perl-JSON-MaybeXS perl-Test-LeakTrace perl-Throwable libmaxminddb-devel";
 
 # the array of perl modules needed
 ARMOD=();
@@ -416,16 +416,24 @@ ARMOD+=('Mail::SpamAssassin');
 
 # not required but nice to have
 ARMOD+=('bignum');				
-ARMOD+=('Data::Dump');			ARMOD+=('DB_File');				ARMOD+=('DBD::SQLite');
-ARMOD+=('DBI');					ARMOD+=('Digest');				ARMOD+=('Encode::Detect');
-ARMOD+=('Error');				ARMOD+=('ExtUtils::CBuilder');	ARMOD+=('ExtUtils::ParseXS');
-ARMOD+=('Getopt::Long');		ARMOD+=('Inline');				ARMOD+=('IO::String');	
-ARMOD+=('IO::Zlib');			ARMOD+=('IP::Country');			ARMOD+=('Mail::SPF');
-ARMOD+=('Mail::SPF::Query');	ARMOD+=('Module::Build');		ARMOD+=('Net::CIDR::Lite');
-ARMOD+=('Net::DNS');			ARMOD+=('Net::LDAP');			ARMOD+=('Net::DNS::Resolver::Programmable');
-ARMOD+=('NetAddr::IP');			ARMOD+=('Parse::RecDescent');	ARMOD+=('Test::Harness');
-ARMOD+=('Test::Manifest');		ARMOD+=('Text::Balanced');		ARMOD+=('URI');
-ARMOD+=('version');				ARMOD+=('IO::Compress::Bzip2'); ARMOD+=('Sendmail::PMilter');
+ARMOD+=('Data::Dump');				ARMOD+=('DB_File');					ARMOD+=('DBD::SQLite');
+ARMOD+=('DBI');						ARMOD+=('Digest');					ARMOD+=('Encode::Detect');
+ARMOD+=('Error');					ARMOD+=('ExtUtils::CBuilder');		ARMOD+=('ExtUtils::ParseXS');
+ARMOD+=('Getopt::Long');			ARMOD+=('Inline');					ARMOD+=('IO::String');	
+ARMOD+=('IO::Zlib');				ARMOD+=('IP::Country');				ARMOD+=('Mail::SPF');
+ARMOD+=('Mail::SPF::Query');		ARMOD+=('Module::Build');			ARMOD+=('Net::CIDR::Lite');
+ARMOD+=('Net::DNS');				ARMOD+=('Net::LDAP');				ARMOD+=('Net::DNS::Resolver::Programmable');
+ARMOD+=('NetAddr::IP');				ARMOD+=('Parse::RecDescent');		ARMOD+=('Test::Harness');
+ARMOD+=('Test::Manifest');			ARMOD+=('Text::Balanced');			ARMOD+=('URI');
+ARMOD+=('version');					ARMOD+=('IO::Compress::Bzip2');		ARMOD+=('Sendmail::PMilter');
+ARMOD+=('Math::Int64');				ARMOD+=('IP::Country;;DB_File');	ARMOD+=('namespace::autoclean');
+ARMOD+=('Data::IEEE754');			ARMOD+=('Data::Printer');			ARMOD+=('Data::Validate::IP');
+ARMOD+=('GeoIP2::Country::Reader');	ARMOD+=('List::AllUtils');			ARMOD+=('List::SomeUtils');
+ARMOD+=('List::UtilsBy');			ARMOD+=('MaxMind::DB::Metadata');	ARMOD+=('MaxMind::DB::Reader');
+ARMOD+=('Module::Runtime');			ARMOD+=('Moo');						ARMOD+=('MooX::StrictConstructor');
+ARMOD+=('Role::Tiny');				ARMOD+=('Scalar::List::Utils');		ARMOD+=('strictures');
+ARMOD+=('Sub::Quote');				ARMOD+=('Math::Int128');			ARMOD+=('Net::Works::Network');
+ARMOD+=('MaxMind::DB::Reader::XS');
 
 # additional spamassassin plugins
 ARMOD+=('Mail::SpamAssassin::Plugin::Rule2XSBody');
@@ -505,6 +513,13 @@ if [ $CPANOPTION -eq 1 ]; then
         cd /root/.cpan/CPAN
         $CURL -O https://s3.amazonaws.com/msv5/CPAN/MyConfig.pm
         cd "$THISCURRPMDIR"
+		AUTOCPAN=1
+        # Install cpanminus
+        $ZYPPER  --non-interactive install cpanm
+        if [ $? -ne 0 ]; then
+            echo "Error installing cpanminus, falling back to perl invocation method."
+            AUTOCPAN=0
+        fi
         timewait 1
     fi
 fi
@@ -543,23 +558,6 @@ do
     fi
 done
 
-# CPAN automation invoked?
-if [ -z "${arg_installCPAN+x}" ]; then
-    AUTOCPAN=0
-else
-    if [ $CPANOPTION -eq 1 ]; then
-        AUTOCPAN=1
-        # Install cpanminus
-        $ZYPPER  --non-interactive install cpanm
-        if [ $? -ne 0 ]; then
-            echo "Error installing cpanminus, falling back to perl invocation method."
-            AUTOCPAN=0
-        fi
-    else
-        AUTOCPAN=0
-    fi
-fi
-
 for i in "${ARMOD[@]}"
 do
     perldoc -l $i >/dev/null 2>&1
@@ -587,19 +585,6 @@ if [[ -n "${arg_update+x}" && $AUTOCPAN -ne 0 ]]; then
     cpanm App::cpanoutdated
     cpan-outdated -p | cpanm --force --no-interactive
 fi
-
-# Mail::ClamAV has broken version detection
-# Prepare to patch and install
-# if [[ $CAV -eq 1 && $CPANOPTION -eq 1 ]]; then
-#     cpan -g Mail::ClamAV
-#     package=$(find -name Mail-ClamAV*gz | tail -n1)
-#     tar xzvf $package
-#     packagedir=$(echo $package | sed -e 's/\.tar\.gz//')
-#     patch -p1 $packagedir/Makefile.PL < /usr/share/MailScanner/patch/patch.diff
-#     cd $packagedir
-#     perl Makefile.PL
-#     make install
-# fi
 
 if [ $CPANOPTION -eq 1 ]; then
   # Install MIME::Tools from CPAN even though rpm is present
@@ -741,132 +726,114 @@ if [ -d '/etc/clamav' ]; then
 
 fi
 
-# # using --force option to reinstall the rpm if the same version is
-# # already installed. this will not overwrite configuration files
-# # as they are protected in the rpm spec file
-# $RPM -Uvh $NODEPS MailScanner*noarch.rpm
+# create ramdisk
+if [ $RAMDISK -eq 1 ]; then
+	if [ -d '/var/spool/MailScanner/incoming' ]; then
+		echo "Creating the ramdisk ...";
+		echo;
+		DISK="/var/spool/MailScanner/incoming";
+		FSTYPE=$(df -P -T ${DISK}|tail -n +2 | awk '{print $2}')
 
-# if [ $? -ne 0 ]; then
-#     echo;
-#     echo '----------------------------------------------------------';
-#     echo 'Installation Error'; echo;
-#     echo 'The MailScanner RPM failed to install. Address the required';
-#     echo 'dependencies and run the installer again. Note that electing';
-#     echo 'to use CPAN should resolve dependency errors.';
-#     echo;
-#     echo 'Note that Perl modules need to be available system-wide. A';
-#     echo 'common issue is that missing modules were installed in a ';
-#     echo 'user specific configuration.';
-#     echo;
-# else
-    # create ramdisk
-    if [ $RAMDISK -eq 1 ]; then
-        if [ -d '/var/spool/MailScanner/incoming' ]; then
-            echo "Creating the ramdisk ...";
-            echo;
-            DISK="/var/spool/MailScanner/incoming";
-            FSTYPE=$(df -P -T ${DISK}|tail -n +2 | awk '{print $2}')
+		if [ $FSTYPE != tmpfs ]; then
+			mount -t tmpfs -o size=${RAMDISKSIZE}M tmpfs ${DISK}
+			echo "tmpfs ${DISK} tmpfs rw,size=${RAMDISKSIZE}M 0 0" >> /etc/fstab
+			echo "Enabling ramdisk sync ...";
+			if [ -f '/etc/MailScanner/defaults' ]; then
+				OLD="^ramdisk_sync=0";
+				NEW="ramdisk_sync=1";
+				sed -i "s/${OLD}/${NEW}/g" /etc/MailScanner/defaults
+			fi
+		else
+			echo "${DISK} is already a RAMDISK!"; echo;
+		fi
+	fi
+fi
 
-            if [ $FSTYPE != tmpfs ]; then
-                mount -t tmpfs -o size=${RAMDISKSIZE}M tmpfs ${DISK}
-                echo "tmpfs ${DISK} tmpfs rw,size=${RAMDISKSIZE}M 0 0" >> /etc/fstab
-                echo "Enabling ramdisk sync ...";
-                if [ -f '/etc/MailScanner/defaults' ]; then
-                    OLD="^ramdisk_sync=0";
-                    NEW="ramdisk_sync=1";
-                    sed -i "s/${OLD}/${NEW}/g" /etc/MailScanner/defaults
-                fi
-            else
-                echo "${DISK} is already a RAMDISK!"; echo;
-            fi
-        fi
-    fi
-    
-    /usr/sbin/ms-update-phishing > /dev/null 2>&1
-    
-    # fix the clamav wrapper if the user does not exist
-    if [ -f '/etc/freshclam.conf' ]; then
-        if id -u vscan >/dev/null 2>&1; then
-            #vscan is being used instead of clamav
-            OLDCAVUSR='ClamUser="clamav"';
-            NEWCAVUSR='ClamUser="vscan"'
+/usr/sbin/ms-update-phishing > /dev/null 2>&1
 
-            if [ -f '/usr/lib/MailScanner/wrapper/clamav-wrapper' ]; then
-                perl -pi -e 's/'$OLDCAVUSR'/'$NEWCAVUSR'/;' /usr/lib/MailScanner/wrapper/clamav-wrapper
-            fi
+# fix the clamav wrapper if the user does not exist
+if [ -f '/etc/freshclam.conf' ]; then
+	if id -u vscan >/dev/null 2>&1; then
+		#vscan is being used instead of clamav
+		OLDCAVUSR='ClamUser="clamav"';
+		NEWCAVUSR='ClamUser="vscan"'
 
-            mkdir -p /var/run/clamav
-            chown vscan:vscan /var/run/clamav
-        fi
-    fi
+		if [ -f '/usr/lib/MailScanner/wrapper/clamav-wrapper' ]; then
+			perl -pi -e 's/'$OLDCAVUSR'/'$NEWCAVUSR'/;' /usr/lib/MailScanner/wrapper/clamav-wrapper
+		fi
 
-    ldconfig
+		mkdir -p /var/run/clamav
+		chown vscan:vscan /var/run/clamav
+	fi
+fi
 
-    if [[ -n "${arg_update+x}" ]]; then
-        echo;
-        echo '----------------------------------------------------------';
-        echo 'Configuration and module update complete';
-        echo;
-        echo 'See http://www.mailscanner.info for more information and  '
-        echo 'support via the MailScanner mailing list.'
-        echo;
-        echo;
-        echo To finish updating MailScanner, review the following files:
-        echo
-        echo /etc/MailScanner/defaults
-        echo /etc/MailScanner/MailScanner.conf
-        echo
-        echo Restart MailScanner
-        echo
-        echo    --SysV Init--
-        echo    service mailscanner restart
-        echo
-        echo    --Systemd--
-        echo    systemctl restart mailscanner.service
-        echo
-        echo Restart MSMilter \(if in use\) 
-        echo
-        echo    --SysV Init--
-        echo    service msmilter restart
-        echo
-        echo    --Systemd--
-        echo    systemctl restart msmilter.service
-        echo
-    else
-        echo;
-        echo '----------------------------------------------------------';
-        echo 'Initial configuration and module installation complete';
-        echo;
-        echo 'See http://www.mailscanner.info for more information and  '
-        echo 'support via the MailScanner mailing list.'
-        echo;
-        echo;
-        echo To finish configuring MailScanner, edit the following files:
-        echo
-        echo /etc/MailScanner/defaults
-        echo /etc/MailScanner/MailScanner.conf
-        echo
-        echo
-        echo To activate MailScanner run the following commands:
-        echo
-        echo    --SysV Init--
-        echo    chkconfig mailscanner on
-        echo    service mailscanner start
-        echo
-        echo    --Systemd--
-        echo    systemctl enable mailscanner.service
-        echo    systemctl start mailscanner.service
-        echo
-        echo To activate MSMilter \(if in use\) run the following commands:
-        echo
-        echo    --SysV Init--
-        echo    chkconfig msmilter on
-        echo    service msmilter start
-        echo
-        echo    --Systemd--
-        echo    systemctl enable msmilter.service
-        echo    systemctl start msmilter.service
-        echo
-    fi 
+ldconfig
+
+if [[ -n "${arg_update+x}" ]]; then
+	echo;
+	echo '----------------------------------------------------------';
+	echo 'Configuration and module update complete';
+	echo;
+	echo 'See http://www.mailscanner.info for more information and  '
+	echo 'support via the MailScanner mailing list.'
+	echo;
+	echo;
+	echo To finish updating MailScanner, review the following files:
+	echo
+	echo /etc/MailScanner/defaults
+	echo /etc/MailScanner/MailScanner.conf
+	echo
+	echo Restart MailScanner
+	echo
+	echo    --SysV Init--
+	echo    service mailscanner restart
+	echo
+	echo    --Systemd--
+	echo    systemctl restart mailscanner.service
+	echo
+	echo Restart MSMilter \(if in use\) 
+	echo
+	echo    --SysV Init--
+	echo    service msmilter restart
+	echo
+	echo    --Systemd--
+	echo    systemctl restart msmilter.service
+	echo
+else
+	echo;
+	echo '----------------------------------------------------------';
+	echo 'Initial configuration and module installation complete';
+	echo;
+	echo 'See http://www.mailscanner.info for more information and  '
+	echo 'support via the MailScanner mailing list.'
+	echo;
+	echo;
+	echo To finish configuring MailScanner, edit the following files:
+	echo
+	echo /etc/MailScanner/defaults
+	echo /etc/MailScanner/MailScanner.conf
+	echo
+	echo
+	echo To activate MailScanner run the following commands:
+	echo
+	echo    --SysV Init--
+	echo    chkconfig mailscanner on
+	echo    service mailscanner start
+	echo
+	echo    --Systemd--
+	echo    systemctl enable mailscanner.service
+	echo    systemctl start mailscanner.service
+	echo
+	echo To activate MSMilter \(if in use\) run the following commands:
+	echo
+	echo    --SysV Init--
+	echo    chkconfig msmilter on
+	echo    service msmilter start
+	echo
+	echo    --Systemd--
+	echo    systemctl enable msmilter.service
+	echo    systemctl start msmilter.service
+	echo
+fi 
 
 ) 2>&1 | tee -a /var/log/mailscanner-configuration.log
