work update
none

diff --git a/common/usr/sbin/ms-check b/common/usr/sbin/ms-check
--- a/common/usr/sbin/ms-check
+++ b/common/usr/sbin/ms-check
@@ -1,13 +1,12 @@
 #!/bin/sh
 #
-#  ms-check
+# ms-check
+# 
+# checks to see if the mailscanner process is running. starts the process
+# unless it has been manually stopped.
 #
-#  $Id: ms-check 5042 2010-07-12 08:02:12Z sysjkf $
-#
-#  Script to check whether mailscanner process is running, and
-#  start it up if not.
-#
-#  Copyright (C) 2002  Julian Field, Nick Phillips
+# author: 	Jerry Benton <mailscanner@mailborder.com>
+#			28 APR 2016
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -26,98 +25,95 @@
 #      https://www.mailscanner.info
 #
 
-# Check that the virus scanner is still running.
-# Re-start it if necessary.
-# This can also be used from the init script to
-# start it in the first place.
-# This can be called with a "-q" command-line option so that it is quiet
-# unless MailScanner actually had to be started.
-
-process=MailScanner
-msbindir=/usr/sbin
-config=/etc/MailScanner/MailScanner.conf
-
-# These seem to get put all over the shop...
-PATH=/usr/bin:/bin
+PATH=$PATH:/usr/sbin:/usr/bin:/bin:/sbin
 export PATH
-PERL=perl
-AWK=awk
-GREP=grep
-FGREP=fgrep
-EGREP=egrep
-PGREP=pgrep
-PS=ps
-UNAME='uname -a'
+NAME=MailScanner
+DAEMON=/usr/sbin/MailScanner
+QUICKPEEK=/usr/sbin/ms-peek
+run_mailscanner=0
+ramdisk_sync=0
+ms_conf=/etc/MailScanner/MailScanner.conf
+ms_core=/usr/share/MailScanner
+ms_lib=/var/lib/MailScanner
+ramdisk_store=/var/spool/MailScanner/ramdisk_store
+stopped_lockfile=/var/lock/subsys/MailScanner.off
+HOSTNAME=$(hostname)
+export HOSTNAME
 
-#TAINTWARN='-Tw'
-TAINTWARN=
+# enable logging of non-critical notices to the maillog: yes/no
+VERBOSE=yes
 
-RETVALUE=" Done."
-# If this does not work on your system, please don't
-# just send us a version that does, please please please
-# send example output that demonstrates *why* it doesn't
-# work, what version of what system you are running etc.
-# If you do this then I *will* make this work right for
-# everybody.
-# -- Nick Phillips <nwp@lemon-computing.com>
-
-if $UNAME | $FGREP "SunOS" >/dev/null ; then
-    # Version for Solaris/SysV systems:
-    pid=`$PGREP $process`
-elif $UNAME | $FGREP "HP" >/dev/null ; then
-    # Version for HP-UX
-    pid=`ps -efx |
-         fgrep $msbindir/$process |
-         fgrep -v fgrep |
-         awk '{print $2}'`
-elif $UNAME | $FGREP "SCO" >/dev/null ; then
-    pid=`ps -e -o pid -o args |
-         fgrep $msbindir/$process |
-         grep -v grep |
-         sed -e 's/^  *//' -e 's/ .*//'`
-elif $UNAME | $FGREP "Linux" >/dev/null ; then
-    pid=`$PS axww |
-         $EGREP $process'[:]|\['$process'\]|[ ]'$msbindir/$process |
-         awk '{ print $1 }'`
-elif $UNAME | $FGREP "BSD" >/dev/null ; then
-    pid=`$PS -axww |
-         $EGREP '[ ]('$msbindir/$process')|'$process'[:]' |
-         $AWK '{print $1}'`
-elif $UNAME | $FGREP "OSF" >/dev/null ; then
-    pid=`ps -e -o pid -o args |
-	$GREP '[ ]'$process |
-	grep -v grep |
-	awk '{ print $1 }'`
-elif $UNAME | $FGREP "Darwin" >/dev/null ; then # ie Mac OSX
-    pid=`$PS axww |
-	$EGREP '[ ]('$msbindir/$process')|'$process'[:]' |
-	$AWK '{print $1}'`
+# basic config file
+if [ -f /etc/MailScanner/defaults ] ; then
+	. /etc/MailScanner/defaults
 else
-    # not BSD; everything else seems to do POSIX
-    pid=`COLUMNS=500 $PS -ef |
-         $EGREP '([ ]'$msbindir/$process')|'$process'[:]' |
-         $AWK '{print $2}'`
+	echo "Aborted: missing configuration file /etc/MailScanner/defaults"
+    exit 1
 fi
 
-# Not needed after 4.61.6.
-## Make it run SpamAssassin out of tmpfs
-#if [ -d /dev/shm ]; then
-#  TMPDIR=/dev/shm
-#  export TMPDIR
-#fi
+PIDFILE=`${QUICKPEEK} PIDFile ${ms_conf}`
 
-if [ "x$pid" = "x" ]; then
-  # Quietly try to raise the open_files limit
-  ulimit -n 2000 >/dev/null 2>&1
-  # Restart it
-  PATH=${msbindir}:$PATH
-  echo -n 'Starting MailScanner ...'
-  cd $msbindir
-  $process $config 2>/dev/null || RETVALUE=" Failed."
-  echo "$RETVALUE"
-else
-  if [ "x$1" != "x-q" ]; then
-    echo MailScanner running with pid $pid
-  fi
+if [ -z $PIDFILE ]; then
+	PIDFILE=/var/run/MailScanner.pid
 fi
 
+# Exit if the MailScanner executable is not installed
+[ -x $DAEMON ] || exit 0
+
+# if /var/lock/subsys is missing
+[ -d /var/lock/subsys ] || mkdir -p /var/lock/subsys
+
+# Don't start if MailScanner is not configured
+if [ $run_mailscanner = 0 ]; then
+	exit 0
+fi
+
+# check if a PID file exists
+if [ -f $PIDFILE ] ; then
+	# get the PID
+	PID=$(head -n 1 $PIDFILE)
+	# check to see if running and belongs to mailscanner
+	ps wwp $PID|grep -iq [M]ailScanner > /dev/null 2>&1
+
+	# get the return
+	RETVAL="$?"
+
+else
+	RETVAL=9
+fi
+
+# if 0 it is already running
+if [ $RETVAL -eq 0 ]; then
+	# already running
+	exit 0
+else
+
+	# if the stopped lock file is present exit
+	if [ -f $stopped_lockfile ] ; then
+		[ "$VERBOSE" != no ] && logger -i -p mail.notice "ms-check: not starting - lock file found"
+		exit 0
+	fi
+	
+	# remove the PID file if preset
+	if [ -f $PIDFILE ] ; then
+		rm -f $PIDFILE
+	fi
+	
+	# kill any rogue processes
+	kill -15 $(ps axww | grep -i [M]ailScanner | awk '{print $1}') > /dev/null 2>&1
+	
+
+	# log the start
+	[ "$VERBOSE" != no ] && logger -i -p mail.notice "ms-check: starting mailscanner"
+	
+	# start mailscanner
+	$DAEMON $ms_conf
+	
+	# set run file
+	if [ ! -f /run/lock/subsys/MailScanner ] ; then
+		touch /run/lock/subsys/MailScanner
+	fi
+	
+	exit 0
+	
+fi
diff --git a/common/usr/sbin/ms-msg-alert b/common/usr/sbin/ms-msg-alert
--- a/common/usr/sbin/ms-msg-alert
+++ b/common/usr/sbin/ms-msg-alert
@@ -1,9 +1,26 @@
 #!/bin/sh
 
-noticesfrom=`/usr/sbin/ms-peek noticesfrom /etc/MailScanner/MailScanner.conf`
-localpostmaster=`/usr/sbin/ms-peek localpostmaster /etc/MailScanner/MailScanner.conf`
-noticesto=`/usr/sbin/ms-peek noticesto /etc/MailScanner/MailScanner.conf`
-sendnotices=`/usr/sbin/ms-peek sendnotices /etc/MailScanner/MailScanner.conf`
+# send alert to administrator about emails mailscanner is 
+# having problems processing
+#
+# created:	Jerry Benton <mailscanner@mailborder.com>
+#			28 APR 2016
+
+ms_conf=/etc/MailScanner/MailScanner.conf
+
+# basic config file
+if [ -f /etc/MailScanner/defaults ] ; then
+	. /etc/MailScanner/defaults
+else
+	logger -i -p mail.notice "ERROR: ms-msg-alert missing configuration file /etc/MailScanner/defaults"
+	echo "Aborted: missing configuration file /etc/MailScanner/defaults"
+    exit 1
+fi
+
+noticesfrom=`/usr/sbin/ms-peek noticesfrom ${ms_conf}`
+localpostmaster=`/usr/sbin/ms-peek localpostmaster ${ms_conf}`
+noticesto=`/usr/sbin/ms-peek noticesto ${ms_conf}`
+sendnotices=`/usr/sbin/ms-peek sendnotices ${ms_conf}`
 
 # Only do this if they want to send notices to postmaster at all
 if [ "x$sendnotices" = "xno" ]; then
@@ -23,7 +40,7 @@ if [ \! "x$alert" = "x" ]; then
   #cat <<EOM
   sendmail -oem -t <<EOM
 From: $noticesfrom <$localpostmaster>
-To: MailScanner Administrator <$noticesto>
+To: Administrator <$noticesto>
 Subject: Problem Messages
 
 $alert
@@ -32,4 +49,3 @@ $alert
 MailScanner
 EOM
 fi
-
diff --git a/common/usr/sbin/ms-update-sa b/common/usr/sbin/ms-update-sa
--- a/common/usr/sbin/ms-update-sa
+++ b/common/usr/sbin/ms-update-sa
@@ -1,15 +1,28 @@
 #!/bin/bash
 
+# created:	Jerry Benton <mailscanner@mailborder.com>
+#			28 APR 2016
+
 SAUPDATE=/usr/bin/sa-update
 SACOMPILE=/usr/bin/sa-compile
-SAUPDATEARGS=""
+ms_re2c=/usr/bin/re2c
+SAUPDATEARGS="--refreshmirrors"
+
+# basic config file
+if [ -f /etc/MailScanner/defaults ] ; then
+	. /etc/MailScanner/defaults
+else
+	logger -i -p mail.notice "ERROR: ms-update-sa missing configuration file /etc/MailScanner/defaults"
+	echo "Aborted: missing configuration file /etc/MailScanner/defaults"
+    exit 1
+fi
 
 export SAUPDATE
 export SACOMPILE
 export SAUPDATEARGS
 UPDATESUCCESS=0
 COMPILESUCCESS=0
-LOGFILE=/tmp/ms-update-sa.$(date +%m%d)
+LOGFILE=/tmp/ms-update-sa.$(date +%m%d%H%M%S)
 
 # Update SpamAssassin rules
 [ -x $SAUPDATE ] || exit 0
@@ -19,20 +32,21 @@ UPDATESUCCESS=$?
 
 if [ $UPDATESUCCESS = 0 ]; then
   # If we have sa-compile and they are using the Rule2XSBody plugin then compile
-  if test -x $SACOMPILE && grep -q '^loadplugin.*Rule2XSBody' /etc/mail/spamassassin/*pre 2>/dev/null ; then
+  if test -x $SACOMPILE && -x $ms_re2c && grep -q '^loadplugin.*Rule2XSBody' /etc/mail/spamassassin/*pre 2>/dev/null ; then
     $SACOMPILE >>$LOGFILE 2>&1
     COMPILESUCCESS=$?
   else
-    echo $SACOMPILE does not exist or Rule2XSBody plugin not enabled >>$LOGFILE
+    echo missing $SACOMPILE or $ms_re2c or Rule2XSBody plugin not enabled >>$LOGFILE
     COMPILESUCCESS=1
   fi
 fi
 
-/etc/init.d/mailscanner reload >>$LOGFILE 2>&1
+/var/lib/MailScanner/init/mailscanner reload >>$LOGFILE 2>&1
 
 # Only delete the logfile if the update succeeded
 if [ $UPDATESUCCESS = 0 -a $COMPILESUCCESS = 0 -o $UPDATESUCCESS = 1 ]; then
-  rm -f $LOGFILE
+	logger -i -p mail.notice "ms-update-sa: spamassassin signatures updated"  	
+	rm -f $LOGFILE
 fi
 
 exit 0
diff --git a/common/usr/sbin/ms-update-vs b/common/usr/sbin/ms-update-vs
--- a/common/usr/sbin/ms-update-vs
+++ b/common/usr/sbin/ms-update-vs
@@ -1,9 +1,25 @@
 #!/bin/sh
 
-SCANNERSCONF=/etc/MailScanner/virus.scanners.conf
-LOCKDIR=`/usr/sbin/ms-peek lockfiledir /etc/MailScanner/MailScanner.conf`
-RUNASU=`/usr/sbin/ms-peek runasuser /etc/MailScanner/MailScanner.conf`
-RUNASG=`/usr/sbin/ms-peek runasgroup /etc/MailScanner/MailScanner.conf`
+# update virus scanners 
+
+# updated: 	Jerry Benton <mailscanner@mailborder.com>
+#			28 APR 2016
+
+ms_conf=/etc/MailScanner/MailScanner.conf
+ms_vs_conf=/etc/MailScanner/virus.scanners.conf
+
+# basic config file
+if [ -f /etc/MailScanner/defaults ] ; then
+	. /etc/MailScanner/defaults
+else
+	logger -i -p mail.notice "ERROR: ms-update-vs missing configuration file /etc/MailScanner/defaults"
+	echo "Aborted: missing configuration file /etc/MailScanner/defaults"
+    exit 1
+fi
+
+LOCKDIR=`/usr/sbin/ms-peek lockfiledir ${ms_conf}`
+RUNASU=`/usr/sbin/ms-peek runasuser ${ms_conf}`
+RUNASG=`/usr/sbin/ms-peek runasgroup ${ms_conf}`
 
 Disabled=no
 if [ "x$Disabled" = "xyes" ]; then
@@ -35,7 +51,7 @@ fi
 [ -x /usr/sbin/ms-create-locks ] && \
 /usr/sbin/ms-create-locks "$LOCKDIR" "$RUNASU" "$RUNASG"
 
-cat ${SCANNERSCONF} | sed -e 's/#.*$//' | ${GREP} -e -wrapper | \
+cat ${ms_vs_conf} | sed -e 's/#.*$//' | ${GREP} -e -wrapper | \
 while read NAME WRAPPER PACKAGEDIR
 do
   #echo String is $NAME $WRAPPER $PACKAGEDIR
@@ -47,11 +63,11 @@ do
     if ${WRAPPER} "${PACKAGEDIR}" -IsItInstalled
     then
       #echo Found $NAME installed
-      logger -p mail.info -t update.virus.scanners Found $NAME installed
+      logger -p mail.notice -t "ms-update-vs Found $NAME installed"
       if [ -x ${UPDATER} ]
       then
         #echo Updating $NAME
-        logger -p mail.info -t update.virus.scanners Running autoupdate for $NAME
+        logger -p mail.info -t "ms-update-vs Running autoupdate for $NAME"
         ${UPDATER} "${PACKAGEDIR}" "${LOCK}" >/dev/null 2>&1
       fi
     fi
