perl-Net-LibIDN for EL9 tidy package list

diff --git a/rhel/usr/sbin/ms-configure b/rhel/usr/sbin/ms-configure
--- a/rhel/usr/sbin/ms-configure
+++ b/rhel/usr/sbin/ms-configure
@@ -33,6 +33,7 @@ while [ $# -gt 0 ]; do
             arg_installPowerTools=0;
             arg_installTNEF=0;
             arg_installUnrar=0;
+            arg_installidn=0;
             arg_SELPermissive=0;
             arg_update=1;
             ((parsedCommands++));
@@ -151,6 +152,19 @@ while [ $# -gt 0 ]; do
             fi
         ;;
 
+        --installidn=*)
+            if [[ ${1#*=} =~ ^([yY])$ ]]; then
+                arg_installidn=1;
+                ((parsedCommands++));
+            elif [[ ${1#*=} =~ ^([nN])$ ]]; then
+                arg_installidn=0;
+                ((parsedCommands++));
+            else
+                printf "Error: Invalid value for installidn: only Y or N values are accepted.\n"
+                exit 1
+            fi
+        ;;
+
         --SELPermissive=*)
             if [[ ${1#*=} =~ ^([yY])$ ]]; then
                 arg_SELPermissive=1;
@@ -191,6 +205,8 @@ while [ $# -gt 0 ]; do
             printf -- "--installTNEF=Y|N       Install tnef via RPM                                            (Y or N)\n"
             printf    "                        Recommended: Y (yes)\n\n"
             printf -- "--installUnrar=Y|N      Install unrar via RPM                                           (Y or N)\n"
+            printf    "                        Recommended: Y (yes)\n\n"
+            printf -- "--installidn=Y|N        Install perl-Net-LibIDN via RPM (EL 9 Only)                     (Y or N)\n"
             printf    "                        Recommended: Y (yes)\n\n"
             printf -- "--installCPAN=Y|N       Install missing perl modules via CPAN                           (Y or N)\n"
             printf    "                        Recommended: Y (yes)\n\n"
@@ -512,6 +528,34 @@ if [ -z "${arg_installUnrar+x}" ]; then
 else
     UNRAROPTION=${arg_installUnrar}
 fi
+
+if [ $RHEL -eq 9 ]; then
+    # ask if the user wants to install perl-Net-LibIDN by RPM if missing
+    clear
+    echo;
+    echo "Do you want to install perl-Net-LibIDN via RPM if missing?"; echo;
+    echo "I will attempt to install perl-Net-LibIDN via the Yum Package Manager, but if not found I can ";
+    echo "install this from an RPM provided by MailScanner Community Project. perl-Net-LibIDN allows";
+    echo "SpamAssassin to handle internationalized domain names.";
+    echo;
+    echo "Recommended: Y (yes)"; echo;
+    if [ -z "${arg_installidn+x}" ]; then
+        read -r -p "Install missing perl-Net-LibIDN via RPM? [n/Y] : " response
+        if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
+            # user wants to use RPM for missing perl-Net-LibIDN
+            IDNOPTION=1
+        elif [ -z $response ]; then 
+            # user wants to use RPM for missing perl-Net-LibIDN
+            IDNOPTION=1
+        else
+            # user does not want to use RPM
+            IDNOPTION=0
+        fi
+    else
+        IDNOPTION=${arg_installidn}
+    fi
+fi
+
 # ask if the user wants missing modules installed via CPAN
 clear
 echo;
@@ -623,7 +667,19 @@ else
 fi
 
 # base system packages
-BASEPACKAGES="binutils gcc glibc-devel libaio make man-pages man-pages-overrides patch rpm tar time unzip which zip libtool-ltdl perl curl wget openssl openssl-devel bzip2-devel libmaxminddb-devel libidn-devel libidn2-devel pyzor re2c unrar tnef p7zip p7zip-plugins sudo"
+BASEPACKAGES="
+            binutils            gcc             glibc-devel 
+            libaio              make            man-pages 
+            man-pages-overrides patch           rpm
+            tar                 time            unzip
+            which               zip             libtool-ltdl
+            perl                curl            wget
+            openssl             openssl-devel   bzip2-devel
+            libmaxminddb-devel  libidn-devel    libidn2-devel
+            pyzor               re2c            unrar
+            tnef                p7zip           p7zip-plugins
+            sudo
+"
 
 # Packages (maybe) available in the yum base of RHEL 7,8,9
 # and EPEL. If the user elects not to use EPEL or if the 
@@ -941,6 +997,35 @@ if [ $UNRAROPTION -eq 1 ]; then
         # back to where i started
         rm -f unrar-6.2.5*
         cd "$THISCURRPMDIR"
+    fi
+fi
+
+if [ $RHEL -eq 9 ]; then
+    # install missing perl-Net-LibIDN if the user elected to do so
+    if [ $IDNOPTION -eq 1 ]; then
+        # user elected to use perl-Net-LibIDN RPM option
+        $RPM -q perl-Net-LibIDN
+        if [ $? -ne 0 ]; then
+            cd /tmp
+            rm -f perl-Net-LibIDN-0.12*
+            clear
+            echo;
+            echo "perl-Net-LibIDN missing. Installing via RPM ..."; echo;
+
+            if [ $RHEL -eq 9 ]; then
+            $CURL -LO https://mirrors.efa-project.org/msv5/EL9/perl-Net-LibIDN-0.12-1.x86_64.rpm
+            if [ -f 'perl-Net-LibIDN-0.12-1.x86_64.rpm' ]; then
+                $RPM -Uvh perl-Net-LibIDN-0.12-1.x86_64.rpm
+            fi
+            else
+            echo "NOTICE: I cannot find a suitable RPM to install perl-Net-LibIDN";
+            timewait 5
+            fi
+            
+            # back to where i started
+            rm -f perl-Net-LibIDN-0.12*
+            cd "$THISCURRPMDIR"
+        fi
     fi
 fi
 
